### ISSUE TITLE
Add support for `all_fields`

### ISSUE THREAD

**Issue by patrick91** [strawberry-graphql/strawberry-graphql-django#106]
In Strawberry's pydantic extension we have support `all_fields`. I think we should add it for strawberry django too :)

https://strawberry.rocks/docs/integrations/pydantic#pydantic-support

**Comment by viaregio** [comment]
Personally I think all_fields is not the way to go. Other libraries like django-ninja or djantic have a more useful mechnanism where you can include or exclude fields.

How do you include all fields except one or two fields?

**Comment by bellini666** [comment]
I have mixed feelings regarding this...

Coming from graphene myself, I feel that automatically exposing all fields from the django model is can lead to a lot of security issues.

For example, I used to love the simplicity of having everything exposed and only defining a few `"exclude"` that should not be exposed, but one day we had an issue with some leaked sensitive information that got exposed by mistake when someone added a new column and forgot to add it to the `"exclude"` list. Since then we changed everything to a "opt-in" approach instead of "opt-out".

Having said that, I don't fully oppose to the ideas here, but I think that if it gets implemented, it should be documented with a "warning" message mentioning that possibility of sensitive data leak by mistake.

Regarding the implementation, we have 2 use cases here:

1) We have an "opt-in" approach, which is basically the way the integration works right now. I don't see a reason to why we would require a `"fields"` list since the current approach of defining that "list" as attributes of the type, and typing them as "auto" is almost as simple as the list itself.

2) We have an "all-in"/"opt-out" approach in which we assume that all fields are included by default, and we can define some to be "excluded". We could go with a new argument `all_fields=True` (false by default) that triggers the "include all fields" introspection, and an optional `exclude_fields` list that defines a list of fields to be excluded when `all_fields is True`

> This would ease a lot the migration from graphene-django, to be fair

There are a lot of people migrating from graphene to strawberry (I'm also included in that list), I imagine if it would be worth to write a small compatibility layer to apply on top of graphene types/fields to transform them into strawberry ones, which would allow people to migrate more easily instead of having to make an "all or nothing" migration.

**Comment by Lucasmiguelmac** [comment]
I am really in favor of implementing the features described in this thread. Though I have some notes on top of what has already been discussed and argued:

* Regarding an `all_fields` implementation:
  * I think if we were to implement an `all_fields` flag, this should not be implemented as in __Pydantic__ (that is, passing `all_fields=False` to the class constructor). I propose we instead follow the already __"djangonic"__ pattern of setting field-inclusion related logic as `class.Meta` fields (or something similar to `class.Meta` that is more adequate for _dataclasses_). Because that lets us put all field-inclusion related logic in one place.
  * When it comes to the default value of this, we could either set it to `True` by default or set it to `False` and raise an error (that would rise when running `./manage.py check`) if nothing else was set (no explicitly defined fields and no `exclude` or `include` iterables) and maybe even point to a url in the docs for a fields section reference inside the error message.  
* Regarding a `exclude`/`include` implementation:
     * About this
       >  I don't see a reason to why we would require a "fields" list since the current approach of defining that "list" as attributes of the type, and typing them as "auto" is almost as simple as the list itself.
       
       I argue that only typing the field name is not "almost as easy" as manually typing each field alongside it's type. Every time you change a model's field type, you'll have to go back and change it again in the type definition (which you might also have a hard time picking if you are new to typed Python and don't know your way around `Optional` and `UNSET`). Needless to say this is not a zero-sum game, by implementing this feature you don't loose the ability to manually type each field if you wished so still.
  *  About this:
      > it should be documented with a "warning" message mentioning that possibility of sensitive data leak by mistake.
  
      If the argument in favor of implementing a warning for the (btw pretty much default Django logic style, followed in forms and serializers as well) `all_fields`, `include`, `exclude` features  is that it this feature is prone to human error (in this case, someone might include a new sensitive field in their model that could be exposed), we might as well forbid all kinds of framework simplifications. Checking that a piece of logic behaves as expected is the job of unit tests.
  * Again this time, a security/simplicity tradeoff shouldn't even necessarily exist. If we were to implement the `all_fields` and set it to `False` by default. The developer could either opt to manually and explicitly set all the fields as @bellini666  suggests or, he could opt to set them inside in any of the automatic options (`all_fields`, `include`, `exclude`). If he does none he'll see an error asking him to set the fields for the type representation.

The key takeaways of my intervention are that:
1. We shouldn't create a framework around "baby-proofing" everything at the expense of simplicity. That doesn't mean we shouldn't make our framework safer when the positive tradeoff is self evident (i.e: setting `all_fields=False` by default as I pointed out earlier).
2. When in doubt, we have the example of DRF and Django itself and they (the contributors) already implemented such features. We are already on top of Django why break such a succesful pattern?

**Comment by Arno500** [comment]
@Lucasmiguelmac It is really similar to the approach used by graphene-django, with the ability to pass an empty `exclude` list to include everything

**Comment by Lucasmiguelmac** [comment]
> @Lucasmiguelmac It is really similar to the approach used by graphene-django, with the ability to pass an empty `exclude` list to include everything

Yes

**Comment by bellini666** [comment]
Hey @Lucasmiguelmac and everyone interested here,

I totally get your points, and as I mentioned previously, I don't fully oppose to the idea and I think that it should be fine to have support for it if that's something people really wants, but still, based on the fact that the whole strawberry philosophy is to use dataclasses + typing and map those the closest as possible to graphql, I would take care to not consider that as the "default way" but a "you can also do this if you need".

Even `auto` is somewhat magical and goes against that philosophy, but is a necessary evil for simplicity of the integration.

> Needless to say it would be awesome to use Djantic itself in the implementation.

I don't think we need to add Djantic as a dependency here, the implementation here would actually me even simples IMO.

Basically, when someone wants to use this feature, he would need to inherit from a base class that has a custom metaclass. That metaclass would access the type's `Meta` (or `Config`) to retrieve the model and the fields (defined as `include`, `exclude`, etc) and inject the fields name in the class's `__dict__` and also put an `auto` in the `__annotattions__`. Then the `strawberry.django.type` would take care of creating the type correctly, just like if you added those fields by hand.

The only complex part here would be to handle references like in this example:

```python
@strawberry.django.type(models.Fruit)
class Fruit:
    id: auto
    name: auto
    color: 'Color'

@strawberry.django.type(models.Color)
class Color:
    id: auto
    name: auto
    fruits: List[Fruit]
```

Both `Fruit.color` and `Color.fruits` can't be automatically resolved easily because `strawberry-django` doesn't keep a registry of `model => type` mapping. It would be necessary to create such mapping, and also allow those to be lazily resolved (in the case above, `Fruit` would need to lazily resolve to `Color` since it would be created by the metaclass and also by the `type` decorator before `Color`).

Also it is worth noting that this imposes a natural downside that graphene also have: If you are automatically resolving any `ForeignKey` to `models.Color` to a type created for `Color`, what happens if you have more than one type? For example, you might want to have something like this:

```python
@strawberry.django.type(models.Color)
class Color:
    id: auto
    name: auto

@strawberry.django.type(models.Color)
class ColorWithFruits:
    id: auto
    name: auto
    fruits: List[Fruit]
```

In graphene-django, I already faced this problem and I know that the latest created type for a model would be used because it would override the registry mapping (which is not obvious when first looking at it without looking at its source code). Due to the fact that this is a very specific corner case, it can be easily resolved by not adding `colors` to the `fields` list and defining it with a proper annotation at the class as a workaround, but I think it is worth mentioning.

Having said all of that, I would encourage anyone wanting this feature to try to open a PR and I'll gladly review it to incorporate into the source code. Feel free to also ping me on discord if you need any help with the implementation :)

**Comment by ccsv** [comment]
For graphene I think it was a meta class used to do the `all_fields`

So they have:
```
class Object:
       class Meta:
              model =Django model
               fields =  (fields, fields)a list of fields or  "__all__" for all fields
              exclude =(fields, fields) an option for fields to exclude
```

If this was implemented in strawberry to be similar I would think you want something like this

```
@strawberry.django.type(models.Fruit)
class Fruits:
    Optional fields: type
    class Meta:
          fields = "__all__" or (List of fields)
          exclude= (List of fields)


```
This format uses more characters than Graphene, we probably want to come up with something with less characters.

**Comment by bellini666** [comment]
This was fixed by https://github.com/strawberry-graphql/strawberry-graphql-django/pull/293
