### ISSUE TITLE
Should strawberry-graphql-django be merged into strawberry?

### ISSUE THREAD

**Issue by joeydebreuk** [strawberry-graphql/strawberry-graphql-django#13]
This issue is to discuss whether strawberry-graphql-django should be merged into strawberry, or if it should remain a separate repo.

**Comment by la4de** [comment]
Good question. We have discussed about that but we do not have clear opinion yet. I'd say that just now it's still good to keep them separate until we have stable API and clear vision what we want.

**Comment by BryceBeagle** [comment]
Because the project is _already_ separate, I don't know if we should devote effort towards migrating the project _into_ the core repository just to later consider making it separate again. I think we should instead work on stabilizing the core API such that keeping `strawberry-graphql-django` separate doesn't become a maintenance burden, _and_ that other extensions have a system to work off of.

I don't think it's wise to have a plugin/extension rely on the internals (i.e. not a public API) of the core project, which I think it currently is doing, while also being in a separate repo. If we can create a clear API that external tools can use to extend the library, we can (and imo should) consider keeping them separate.

We can even make use of [namespace packages](https://packaging.python.org/guides/packaging-namespace-packages/) so that `strawberry-graphql-django` can still be imported as `from strawberry.django import ...` (i.e. under the `strawberry` namespace) even if it's a separate package.

---

That being said, if we do decide to combine the two projects now, it's also not impossible to later split the repo. I've got some experience breaking apart mono repos while maintaining git history, and it's not too difficult if there's a clear directory separation within the repo.

**Comment by joeydebreuk** [comment]
@la4de  I think we can close this.
