### ISSUE TITLE
Nested foreign key mutations do not work

### ISSUE THREAD

**Issue by ccsv** [strawberry-graphql/strawberry-graphql-django#133]
See this stackoverflow [post](https://stackoverflow.com/questions/72782586/django-strawberry-writing-a-mutation-that-includes-a-foreign-key-that-creates-mu/72796059#72796059)

The code should produce two different object but did not.

## Describe the Bug
When you create a object with a foreign key object using one mutation there is a error 
`
"message": "Field 'id' expected a number but got PersonInput(id=<strawberry.unset._Unset object at 0x00000194FB945C90>, addressname='jkkihh', description=<strawberry.unset._Unset object at 0x00000194FB945C90>, notes=<strawberry.unset._Unset object at 0x00000194FB945C90>)."`

This makes it not possible to create new objects with foreign keys that are nested because it does not create an id.

## System Information

 - Operating system: Windows 10
 - Strawberry version (if applicable): 0.31
 - Django 4.03

**Comment by bellini666** [comment]
Hey @ccsv , thanks for the report.

Yeah, I don't think we are currently dealing with nested objects creation in strawberry-graphql-django.

I saw that in the issue you mentioned the guy answered that you could use [strawberry-django-plus](https://github.com/blb-ventures/strawberry-django-plus). As the maintainer of that project, I can confirm to you that nested creation works there (if you want to use it, feel free to contact me on discord and I can help you if you have any issues/doubts)

Also, since you mentioned that on stack overflow: Yes, it is my intention to merge most of what is in strawberry-django-plus into strawberry-graphql-django. I am unfortunately lacking time to actually do that, but I hope I can do that soon.
