### ISSUE TITLE
stubs needed for strawberry_django

### ISSUE THREAD

**Issue by brentpicasso** [strawberry-graphql/strawberry-graphql-django#204]
## Feature Request Type

- [X] Core functionality
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

## Description

Hi, we need stubs to be added to strawberry_django, so mypy can be successfully used.

**Comment by bellini666** [comment]
@brentpicasso you can install them in your project and they will be used. The reason I don't think it is a good idea to put them here is because django-stubs package is focused on mypy itself, and relies a lot on plugins to work. There's a fork of it called [django-types](https://github.com/sbdchd/django-types) which removes the plugin dependency for checkers that don't have plugin support (e.g. pyright), and they are not compatible.

**Comment by bellini666** [comment]
I just noticed that my answer here was for django-stubs, while you might be mentioning this repo itself.

For the repo itself, everything was properly types during the v0.10.0 refactor. So this should now be solved :)
