### ISSUE TITLE
One-to-One Models results in errors

### ISSUE THREAD

**Issue by Skyquek** [strawberry-graphql/strawberry-graphql-django#245]
## Describe the Bug

I try to use on-to-one models in strawberry. However, I face this issue: Its might related to this issue mentioned here https://github.com/strawberry-graphql/strawberry-graphql-django/issues/235, but I create a new issue in case the issue is different from that.

models.py
```python
from django.contrib.auth.models import User
class User(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    birthday = models.DateField()
    phone_number = PhoneNumberField(blank=True)
```

schema.py
```python
@strawberry.django.type(DJangoUser)
class DJangoUser:
    username: auto
    first_name: auto
    last_name: auto
    email: auto

@strawberry.django.type(models.User)
class User:
    id: strawberry.ID
    birthday: date
    phone_number: str
    django_user: DJangoUser
```

Error:
```cmd
{
	"data": null,
	"errors": [
		{
			"message": "Field 'djangoUser' argument 'pk' of type 'ID!' is required, but it was not provided.",
			"locations": [
				{
					"line": 4,
					"column": 3
				}
			]
		}
	]
}
```

The details of the code can be look at here https://github.com/Skyquek/Trip-Bill-Management-System/pull/6.

**Comment by bellini666** [comment]
Hey @Skyquek ,

Just looked at your code, and the issue is that to [define if a field is a relation](https://github.com/strawberry-graphql/strawberry-graphql-django/blob/main/strawberry_django/type.py#L71) the code searches for the field in the model definition. In this case, it would look for a field called `django_user` inside your `User` model, which doesn't exist.

You can fix this in two ways:

1) Expose `User.djangoUser` as just `User.user`

2) If you want to use the `djangoUser` name, define it with `django_user: DJangoUser = strawberry_django.field(field_name="user")`. This will tell the field that although it is called `djangoUser` for the graphql api, its django's attribute name is `user`

Please tell me if that works for you

**Comment by Skyquek** [comment]
Thanks for your reply, its work!
