### ISSUE TITLE
Pagination misses full count

### ISSUE THREAD

**Issue by capital-G** [strawberry-graphql/strawberry-graphql-django#266]
## Feature Request Type

- [ ] Core functionality
- [x] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

## Description

Pagination w/o metadata on number of instances allows only for infinite scrolling because it is unclear what the full count of pages is.
Strawberry docs suggest by appending metadata with the number of items.
But it seems this would make the return type more nasty because this would require a wrapper for the actual return type.

https://strawberry.rocks/docs/guides/pagination/overview#pagination-metadata

I'd like to contribute but I must admit that I am somehow lost in the python style of strawberry.

**Comment by bellini666** [comment]
Hey @capital-G ,

You can probably use the relay integration for that: https://strawberry.rocks/docs/guides/relay

I'm currently merging strawberry-django-plus into this lib, which also provides a [ListConnectionWithTotalCount](https://github.com/blb-ventures/strawberry-django-plus/blob/main/strawberry_django_plus/relay.py#L21), which you can already use by copying that code.

Would that work for you?

**Comment by shobu13** [comment]
Heya, same problem here, if you just want to use offset based pagination, you need to make a second request with no limit to get the total count of your objects (querying only the IDs for exemple), using cursor pagination you can't jump on a page, that one use case of offset based pagination.

**Comment by bellini666** [comment]
> Heya, same problem here, if you just want to use offset based pagination, you need to make a second request with no limit to get the total count of your objects (querying only the IDs for exemple), using cursor pagination you can't jump on a page, that one use case of offset based pagination.

The only issue here is that you can get different results on separated queries.

The reason it is not easy to expose a "totalCount" right now is that the returned value is a list of the objects, meaning you would need to actually return a type which has a "totalCount" and the list of objects in those

I recommended using relay pagination because it is already ready for that. Adding a totalCount or any other extra attr to the pagination info is trivial. But it should also not be that hard to implement something custom for that

**Comment by salcedo** [comment]
Using relay has its own set of challenges right now. How do we traverse to other nodes (i.e. django related models) when using a Relay setup?

If using Relay, an example query would look something like this:
```
query FetchPostsWithComments {
  posts {
    totalCount   <-- totalCount of posts
    edges {
      node {
        id
        body
        comments {
          totalCount    <-- totalCount of comments belonging to this post
          edges {
            node {
              id
              body
            }
          }
        }
      }
    }
  }
}
```
Currently there is no documentation in strawberry, strawberry-graphql-django, nor strawberry-django-plus about how to implement an API that allows a query like the above.

It seems this challenge was already discussed here: #79 
I'm okay with the idea of having a dedicated return type that contains a list and a total count, without having to resort to Relay, but I don't know how to approach it in a way that would be close enough to correctness as well as performant.

**Comment by bellini666** [comment]
> Currently there is no documentation in strawberry, strawberry-graphql-django, nor strawberry-django-plus about how to implement an API that allows a query like the above.

Actually that is straightforward:

```python
@strawberry.django.type(Post)
class CommentType(relay.Node):
    pk: relay.NodeID[int]


@strawberry.django.type(Post)
class PostType(relay.Node):
    pk: relay.NodeID[int]

    @relay.connection(relay.ListConnectionWithTotalCount[CommentType]
    def comments(self, root: Post):
        return root.comments.all()


@strawberry.type
class Query:
    @relay.connection(relay.ListConnectionWithTotalCount[PostType]
    def posts(self):
        return Post.objects.all()
```

I'm almost done opening a PR with `Connection` integration in this repo and things will get even easier to use. e.g. For django types there will be no need to define the `relay.NodeID` annotation and by doing `posts: relay.ListConnectionWithTotalCount[PostType]` without a resolver will automatically add a resolver that returns `Post.objects.all()` for you (which also works for nested connections).

> I'm okay with the idea of having a dedicated return type that contains a list and a total count, without having to resort to Relay, but I don't know how to approach it in a way that would be close enough to correctness as well as performant.

I think this mostly depends on if you want pagination or not in the nested list.

If you don't need pagination and will return everything, then it is better to return a list directly. It will allow the optimizer (currently in strawberry-django-plus and soon merged in this repo) for prefetch those, avoiding n+1 issues. For the total count in there you can just get the `length` of the returned list in the client.

If you do need, then you will end up with a solution very similar to relay's one. Maybe with one less level (i.e. no `edges`, `node`, just an object with `totalCount` and `items`). This is a nice "simple" alternative to relay. The only "extra" thing that the relay integration provides by having those extra attributes is the possibility for you to implement a different pagination style (e.g. cursor instead of limit/offset), and also it makes it easier to implement infinite pagination when don't know the number of pages you can have.

**Comment by bellini666** [comment]
Since the relay integration has been merged, I'm closing this since now there's a way to do pagination and getting the full count using `ListConnectionWithTotalCount`.
