### ISSUE TITLE
returning django model causes typing error

### ISSUE THREAD

**Issue by hyusetiawan** [strawberry-graphql/strawberry-graphql-django#349]
returning a django model instance in a query, results in a typing error, example for a model called Chat, for an graphql called ChatObject
`Expression of type "Chat" cannot be assigned to return type "ChatObject"
  "Chat" is incompatible with "ChatObject"` the type checker is pylance

## Describe the Bug
given the following mutation:
```

@strawberry.type
class MutationChat:
    @strawberry.field
    async def create_chat(self, title: str, info: AppInfo) -> ChatObject:
        user = await get_user_from_request(info)
        return await ChatModel.objects.acreate(author=user, title=title)
```
and the ChatObject is:
```

```
@strawberry_django.type(models.Chat, name="Chat")
class ChatObject(Node):
    title: auto
    model: auto
```
The code runs fine, but the typing is reporting errors, like so:
<img width="681" alt="Screenshot 2023-08-27 at 11 52 47 PM" src="https://github.com/strawberry-graphql/strawberry-graphql-django/assets/1062920/c5e14a83-cc6c-45d3-93b4-37d198c33b48">


<!-- A clear and concise description of what the bug is. -->

## System Information

 - Operating system: macos
 - Strawberry version (if applicable):
```
strawberry-graphql==0.205.0
strawberry-graphql-django==0.16.0
```
## Additional Context

<!-- Add any other relevant information about the problem here. -->

**Comment by bellini666** [comment]
Hi @hyusetiawan ,

This is a [known issue](https://github.com/strawberry-graphql/strawberry-graphql-django/issues/256) and unfortunately we don't have a way to solve this elegantly yet.

As I mentioned [in this comment](https://github.com/strawberry-graphql/strawberry-graphql-django/issues/256#issuecomment-1561863544), I'm planning to add PEP 712 support to strawberry so that we may be able to workaround this in the future. In the meantime you can workaround this by doing `return cast(CharObject, await ChatModel.objects.acreate(author=user, title=title))`

I'm gonna close this as it is duplicated of #256 . Feel free to add more thoughts into that issue :)
