### ISSUE TITLE
Improvement in Documentation

### ISSUE THREAD

**Issue by ArcD7** [strawberry-graphql/strawberry-graphql-django#434]
Hey, first of all thanks for building this library. We are creating projects on strawberry django since day1.

Just pointing this out, in the documentation `strawberry.django` and `strawberry_django` are being used as interchangeable terms. Eg in [Mutations](https://strawberry-graphql.github.io/strawberry-graphql-django/guide/mutations/).

I'm not sure, what the difference is between those two, it would be good if we can use either one of them or if they work differently then we can have a section which mentions the difference between them.

**Comment by bellini666** [comment]
Hey @ArcD7 ,

TBH `strawberry.django` and `strawberry_django` should be interchangeable (because of this https://github.com/strawberry-graphql/strawberry/blob/main/strawberry/django/__init__.py), but I usually prefer the later as it behaves better with LSPs and is more straight forward.

This is something that for sure would be nice to improve in the docs!

**Comment by ArcD7** [comment]
Hey @bellini666 , is it okay, if I take this issue?

I guess, it would be a good way to start contributing.

**Comment by bellini666** [comment]
@ArcD7 yeah, go ahead! Contributions are always very welcomed :)

Let me know if you need help with anything. You can either ping me here or on [discord](https://strawberry.rocks/discord)
