### ISSUE TITLE
File field with blank=False fails validation in create mutation

### ISSUE THREAD

**Issue by yergom** [strawberry-graphql/strawberry-graphql-django#468]
Follow up from #461. The PR https://github.com/strawberry-graphql/strawberry-graphql-django/pull/464 has solved saving the instance, but the validation code is still incorrect. FileFields with blank=False will fail validation. 

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry-graphql-django/issues/468">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry-graphql-django/issues/468/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry-graphql-django/issues/468/pledge.svg">
</picture>
</a>

**Comment by bellini666** [comment]
Hi @yergom ,

You mean, a field with `blank=False` should fail the validation if no file upload has been provided to it?

**Comment by yergom** [comment]
Hi @bellini666, no, that's not the case. Let me elaborate.

If you have a field with a non optional file

```py
class MyModel(models.Model):
   file = models.FileField(null=False, blank=False)
```

then the validation fails. The problem is that the `prepare_create_update` method is not setting the file field in the dummy instance.

**Comment by sdobbelaere** [comment]
That's an interesting observation @yergom.  I seem to remember that I refactored the update and create methodes with prepare_create_update.  This was done in order to ensure that creates and updates would respect the manager configurations.  

In order to do that, within the current structure I choose to leave the files outside of that function as it's intended for preparation.  Not for the actual setting of values. 

If we add the files inside of `prepare_create_update`, then it will no longer follow the correct flow for update neither and the entire thing will need refactoring.  

@bellini666 I'll have a play with it inside the create-method and keep it aligned with the dummy_instance.

**Comment by yergom** [comment]
@sdobbelaere I've looked at the PR and it seems correct. At the beginning I had some doubts of calling save_form_data twice, but the file is really committed to the backend in the pre_save method, so it looks good to me! Thanks for fixing this so fast!
